version: '3.8'

services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}  # Use values from .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
