version: '3.8'

services:
  # Node.js service
  app:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"  # Map port 3000 from the container to your machine
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
    depends_on:
      - postgres

  # PostgreSQL service
  postgres:
    image: postgres:14-alpine  # Use the official PostgreSQL image
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Expose port 5432 for database connections
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres-data:
    driver: local
